routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');
Route::get('/search/{q}', 'HomeController@search')->name('search');
Route::get('/currencies', 'HomeController@getCurrencies')->name('currencies');

// Categories
Route::get('/category/{slug}', 'CategoryController@show')->name('category.show');
// Work Ajax only
Route::get('/category/{slug}/articles', 'CategoryController@articles')->name('category.articles');
Route::get('/category/{slug}/section', 'CategoryController@categorySection')->name('category.section');


//Media
Route::get('/media/videos', 'MediaController@videos')->name('media.videos.index');
Route::get('/media/videos/filters', 'MediaController@videosFilters')->name('media.videos.filters');
Route::get('/media/videos/{slug}', 'MediaController@videoShow')->name('media.videos.show');


Route::get('/media/albums', 'MediaController@albums')->name('media.albums.index');
Route::get('/media/albums/{slug}', 'MediaController@albumShow')->name('media.albums.show');


Route::get('/article/{slug}', 'ArticlesController@show')->name('articles.show');

Route::get('/author/{username}', 'ProfileController@index')->name('author.index');
Route::get('/author/{username}/articles', 'ProfileController@articles')->name('author.articles');

Route::get('/pages/{slug}', 'HomeController@page')->name('pages.show');
Route::get('/about-us', 'HomeController@aboutUs')->name('pages.about');
Route::get('/privacy-policy', 'HomeController@privacy')->name('pages.privacy');
Route::any('/contact-us', 'HomeController@contactUs')->name('pages.contact');
Route::get('/tags/{slug}', 'TagsController@show')->name('tags.show');


// SiteMap and rss
Route::get('/sitemap-update', 'SitemapController@update')->name('sitemap.update');
Route::get('/articles_instant.xml', 'FeedController@articles_instant')->name('rss.instant_articles');


Route::post('/poll/answer', 'PollController@pushAnswer')->name('poll.vote');

Route::get('/remedia/{offset}', 'MediaRegeneratController@regenerate_media')->name('media.cron');

//Migration
Route::get('/migration/posts/{offset?}', 'MigrationController@posts')->name('posts.migration');
Route::get('/migration/galleries/{offset?}', 'MigrationController@galleries')->name('galleries.migration');
Route::get('/migration/tags/{offset?}', 'MigrationController@tags')->name('tags.migration');
Route::get('/migration/users/{offset?}', 'MigrationController@users')->name('users.migration');
Route::get('/migration/media/{offset?}', 'MigrationController@media')->name('media.migration');
Route::get('/migration/fiximages/{offset?}', 'MigrationController@postsReContents')->name('post.fix');


Route::group([
    "prefix" => 'ar',
], function ($router) {
    $router->get('/', function () {
        return redirect(route('home'), 301);
    });
    // Video redirect
    $router->get('allVideos', function () {
        return redirect(route('media.videos.index'), 301);
    });
    $router->get('video/{id}/{slug}', function ($id, $slug) {
        return redirect(route('media.videos.show', ['slug' => $slug]), 301);
    });
    // Albums redirect
    $router->get('albums', function () {
        return redirect(route('media.albums.index'), 301);
    });
    $router->get('album/{id}/{slug}', function ($id, $slug) {
        return redirect(route('media.albums.show', ['slug' => $slug]), 301);
    });
    //Sections
    $router->get('section/{id}/{slug}', function ($id, $slug) {
        return redirect(route('category.show', ['slug' => $slug]), 301);
    });

    $router->get('article/{id}/{slug}', function ($id, $slug) {
        return redirect(route('articles.show', ['slug' => $slug]), 301);
    });

});

app/Models/Nav.php
<?php

namespace App\Models;

use Dot\Navigations\Models\Nav as DotNav;

class Nav extends DotNav
{
    /**
     * Generate suit link using type
     * @return string
     */
    public function getPathAttribute()
    {
        return nav_link($this);
    }
}

app/Models/Post.php
<?php

namespace App\Models;


use App\User;
use Carbon\Carbon;
use Dot\Posts\Models\Post as Model;

class Post extends Model
{

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = [
        'published_at'
    ];

    /**
     * @param $query
     * @return mixed
     */
    public function scopePublished($query)
    {
        return $query->status('published')->where('published_at', '<=', Carbon::now())->has('image');
    }


    public function getPublishedAtAttribute()
    {
        return Carbon::createFromFormat('Y-m-d H:i:s',$this->attributes['published_at'])->addHours(2);
    }

    /**
     * @param $query
     * @return mixed
     */
    public function scopeRecently($query)
    {
        return $query->orderBy('published_at', 'DESC');
    }

    /**
     *
     * @return string
     */
    public function getPathAttribute()
    {
        switch ($this->format) {
            case 'post':
                return route('articles.show', ['slug' => $this->slug]);
            case 'video':
                return route('media.videos.show', ['slug' => $this->slug]);
            case 'album':
                return route('media.albums.show', ['slug' => $this->slug]);

        }
        return route('home');
    }

    /**
     *  path_preview
     * @return string
     */
    public function getPathPreviewAttribute()
    {
        switch ($this->format) {
            case 'post':
                return route('articles.show', ['slug' => $this->slug,'preview'=>true]);
            case 'video':
                return route('media.videos.show', ['slug' => $this->slug,'preview'=>true]);
            case 'album':
                return route('media.albums.show', ['slug' => $this->slug,'preview'=>true]);

        }
        return route('home');
    }

    /**
     * @return string
     */
    public function getSmallTitleAttribute()
    {
        return str_limit($this->title, 35, '....');
    }

    /**
     * category_name
     * @return mixed
     */
    public function getCategoryAttribute()
    {
        if (!isset($this->basd_category)) {
            $this->basd_category = $this->categories()->first();
            if(!$this->basd_category){
                $this->basd_category = Category::first();
            }
        }
        return $this->basd_category;
    }

    /**
     * Author relation
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function author()
    {
        return $this->hasOne(User::class, "id", "author_id");
    }

    /**
     * Return Auth name
     */
    public function getAuthorNameAttribute()
    {
        if ((!($author = $this->author)) || $this->author_id == 0) {

            return  $this->user?$this->user->first_name . ' ' . $this->user->last_name:'';
        }
        return $author->first_name . ' ' . $author->last_name;
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function related()
    {
        return $this->belongsToMany(Post::class, "related_posts", "post_id", "related_post_id");
    }

}

resources/views/partials/category-section.blade.php
@php
$category=get_category($slug,$limit);
@endphp
@include('partials.category-section.list',['category'=>$category])

resources/views/partials/currency-and-newsletter.blade.php
<script async
        src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- Sport sections -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-8580090353710615"
     data-ad-slot="6330895867"
     data-ad-format="auto"></ins>
<script>
    (adsbygoogle = window.adsbygoogle || []).push({});
</script>
<div id="sidebar-newsletter">
    <div class="title-style01">
        <h3><strong>سجل لتصلك نشرتنا الإخبارية</strong></h3>
    </div>
    <div class="sidebar-newsletter-form">
        <form class="form-horizontal" action="#" id="subscribeForm"
              method="POST">
            <div class="input-group">
                <input title="Newsletter" class="form-control" name="email" type="email"
                       id="address" placeholder="أدخل البريد الإلكتروني"
                       data-validate="validate(required, email)" required>
                <span class="input-group-btn"> <button type="submit" class="btn btn-success">الإشتراك</button> </span>
            </div>
        </form>
        <span id="result" class="alertMsg"></span>
    </div>
</div>
<div class="sidebar-social-icons">
    <div class="title-style01">
        <h3><strong>تواصل </strong> معنا</h3>
    </div>
    <ul>
        @if(!empty(option('facebook_page')))
            <li>
                <a href="{{option('facebook_page')}}" class="facebook"><i
                            class="fa fa-facebook"></i></a>
            </li>
        @endif
        @if(!empty(option('twitter_page')))
            <li>
                <a href="{{option('twitter_page')}}" class="twitter"><i
                            class="fa fa-twitter"></i></a>
            </li>
        @endif
        @if(!empty(option('youtube_page')))
            <li>
                <a href="{{option('youtube_page')}}" class="youtube"> <i
                            class="fa fa-youtube"></i></a>
            </li>
        @endif
        @if(!empty(option('googleplus_page')))
            <li>
                <a href="{{option('googleplus_page')}}" class="google-plus"><i
                            class="fa fa-google-plus"></i></a>
            </li>
        @endif
        @if(!empty(option('linkedin_page')))
            <li>
                <a href="{{option('linkedin_page')}}" class="linkedin"><i
                            class="fa fa-linkedin"></i></a>
            </li>
        @endif
        @if(!empty(option('instagram_page')))
            <li>
                <a href="{{option('instagram_page')}}" class="instagram"> <i
                            class="fa fa-instagram"></i></a>
            </li>
        @endif
    </ul>
</div>

resources/views/partials/main-bar.blade.php
<!--Start Module -->
<section class="module dark">
    <div class="container">
        <div class="row no-gutter">
            <div class="news-slide">
                @foreach($posts as $post)
                    <div class="col-md-4 col-xs-12 no-pad news-slider-layer">
                        <a href="{{$post->path}}" title="{{$post->title}}">
                            <div class="content">
                                <span class="category-tag bg-4"
                                      style="background-color: {{$post->category->color}}">{{$post->category->name}}</span>
                                <p>{{$post->small_title}}</p>
                            </div>
                            <img src="{{$post->image?thumbnail($post->image->path,'main-bar'):''}}" title="{{$post->title}}" alt="{{$post->title}}">
                        </a>
                    </div>
                @endforeach
            </div>
        </div>
    </div>
</section>
<!--End module -->

resources/views/partials/main-slider-home.blade.php
@include('partials.main-slider',['posts'=>$homeSliderArticles])

resources/views/partials/main-slider.blade.php
@if(!is_mobile())
    <section class="module">
        <div class="container">
            @include('partials.newest-articles')
            <div id="news-slider" class="owl-carousel">
                <?php $classes = ['first', 'second', 'third', 'fourth']; ?>
                <?php $sizes = ['article', 'main-slider-second', 'main-slider-third', 'main-slider-third']; ?>
                @foreach($posts as $post)
                    {!! $loop->index%4==0?'<div class="news-slide">':''!!}
                    <div class="news-slider-layer {{$classes[$loop->index%4]}}">
                        <a href="{{$post->path}}">
                            <div class="content">
                            <span class="category-tag bg-1"
                                  style="background-color: {{$post->category->color}}">{{$post->category->name}}</span>
                                <p>{{$post->title}}</p>
                            </div>
                            <img src="{{thumbnail($post->image->path,$sizes[$loop->index%4])}}" alt="{{$post->title}}"
                                 title="{{$post->title}}"/>
                        </a>
                    </div>
                    {!! $loop->index%4==3?'</div>':''!!}
                @endforeach
            </div>
        </div>
    </section>
@else
    <section class="module">
        <div class="container">
            @include('partials.newest-articles')
            <div class="swiper-container" id="main-slider">
                <div class="swiper-wrapper">
                    @foreach($posts as $post)
                        <div class="swiper-slide" style="min-width: 100%">
                            <div class="news star-news">
                                <div class="item" itemscope itemtype="http://schema.org/Article">
                                    <div class="item-image-1">
                                        <a class="img-link" itemprop="url" content="{{$post->path}}"
                                           title="{{$post->title}}"
                                           href="{{$post->path}}">
                                            <img class="img-responsive img-full"
                                                 src="{{thumbnail($post->image->path,'medium')}}"
                                                 title="{{$post->title}}" alt="{{$post->title}}">
                                        </a>
                                        <span><a class="label-1"
                                                 style="background-color: {{$post->category->color}}"
                                                 href="{{route('category.show',['slug'=>$post->category->slug])}}">{{$post->category->name}}</a></span>
                                    </div>
                                    <div class="item-content">
                                        <div class="title-left title-style04 underline04">
                                            <h3><a href="{{$post->path}}" title="{{$post->title}}"><strong
                                                            itemprop="name">{{$post->title}}</strong></a>
                                            </h3>
                                        </div>
                                        <p><a href="{{$post->path}}" class="external-link">{{$post->excerpt}}</a>
                                        </p>

                                        <div>
                                            <a href="{{route('category.show',['slug'=>$post->category->slug])}}"><span
                                                        class=" read-more"
                                                        itemprop="articleSection">{{$post->category->name}}</span></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    @endforeach
                </div>

                <div class="swiper-button-prev"></div>
                <div class="swiper-button-next"></div>
            </div>
        </div>
    </section>
@endif


@push('scripts')

    <style>
        .swiper-button-prev, .swiper-container-rtl .swiper-button-next {
            left: 10px;
            right: auto;
            top: 120px;
        }

        .swiper-container .item-content {
            min-height: 168px;

        }

    </style>
    @if(is_mobile())
        <script>
            $(function () {

                new Swiper('.swiper-container#main-slider', {
                    slidesPerView: 1,
                    navigation: {
                        nextEl: '.swiper-button-next',
                        prevEl: '.swiper-button-prev',
                    },
                });
            })
        </script>
    @endif
@endpush

resources/views/partials/matches.blade.php
@if(count($leagues)>0)
    <div class="matches-wrapper clearfix">
        <div class="title-style02 survy-title">
            <h3><a href="javascript:void(0)">مباريات اليوم</a></h3>
        </div>
        @foreach($leagues as $title => $matches)
            <h2 class="title title-action ">{{$title}}</h2>
            <hr>
            @foreach($matches as $match)
                <div class="row match-row" style="text-align: center">
                    <div class="col-md-4">
                        <span>{{$match->team_home}} </span>
                    </div>
                    <div class="col-md-1">
                        {{$match->team_home_score?$match->team_home_score:'_'}}

                    </div>
                    <div class="col-md-2">
                        <p>X</p>
                        <p style="width: 39px;">{{arabic_date_hour($match->published_at)}}</p>
                    </div>
                    <div class="col-md-1">
                        {{$match->team_away_score?$match->team_away_score:'_'}}
                    </div>
                    <div class="col-md-4">
                        <span>{{$match->team_away}}</span>
                    </div>
                </div>
            @endforeach
        @endforeach
    </div>
@endif

resources/views/partials/meta.blade.php
<?php $seo = $post->seo; ?>
<meta property="og:locale" content="{{app()->getLocale()}}"/>
<meta property="og:type" content="{{ $type or 'article'}}"/>
<meta name="author" content="{{option('site_name')}}">
<meta name="twitter:site" content="{{'@'.option('site_name')  }}">
<meta name="twitter:card" content="summary_large_image">
<meta property="og:url" content="{{$post->path}}">
<meta name="twitter:url" content="{{$post->path}}">

@if($seo&&!empty($seo))
    <!--seo Object-->
    <meta name="title" content="{{ $seo->meta_title or $post->title}}">
    <meta name="keywords" content="{{$seo->meta_keywords}}">
    <meta name="description" content="{{!empty($seo->meta_description)?$seo->meta_description:$post->excerpt}}"/>
    <meta property="og:title"
          content="{{ !empty($seo->facebook_title)?$seo->facebook_title:(!empty($seo->meta_title)? $seo->meta_title: $post->title)}}"/>
    <meta property="og:site_name" content="{{option('site_name')}}"/>
    <meta property="og:description"
          content="{{ !empty($seo->facebook_description)?$seo->facebook_description:(!empty($seo->meta_description)? $seo->meta_description: $post->excerpt)}}">
    <meta property="og:image"
          content="{{ !empty($seo->facebook)?uploads_url($seo->facebook->path):($post->image ? uploads_url($post->image->path) : '')}}">
    <meta name="twitter:title"
          content="{{!empty($seo->twitter_title)?$seo->twitter_title:(!empty($seo->meta_title)?$seo->meta_title: $post->title) }}">
    <meta name="twitter:description"
          content="{{ !empty( $seo->twitter_description)? $seo->twitter_description : ( !empty($seo->meta_description)?$seo->meta_description:$post->excerpt)}}">
    <meta name="twitter:image"
          content="{{ !empty($seo->twitter)?uploads_url($seo->twitter->path):($post->image ? uploads_url($post->image->path) : '')}}">
@else
    <!--not seo Object-->
    <meta name="title" content="{{ str_limit($post->title,60)}}">
    <meta name="description" content="{{ $post->excerpt}}"/>
    <meta property="og:locale" content="{{app()->getLocale()}}"/>
    <meta property="og:title" content="{{ $post->title}}"/>
    <meta property="og:site_name" content="{{option('site_name')}}"/>
    <meta property="og:description" content="{{ str_limit($post->excerpt,160,'')}}">
    <meta property="og:image" content="{{ ($post->image ? uploads_url($post->image->path) : '') }}">
    <meta name="twitter:title" content="{{$post->title }}">
    <meta name="twitter:description" content="{{ $post->excerpt}}">
    <meta name="twitter:image"
          content="{{ ($post->image ? uploads_url($post->image->path) : '') }}">
    <meta name="twitter:url" content="{{$post->path}}">
@endif

resources/views/partials/newest-articles.blade.php
<div class="outer">
    <div class="breaking-ribbon">
        <h4>أحدث الأخبار</h4>
    </div>
    <div class="newsticker">
        <ul>
            @foreach($posts as $post)
                <li>
                    <h4 title="{{$post->title}}"><span class="category">{{$post->category->name}}
                            :</span><a
                                href="{{$post->path}}" title="{{$post->title}}">{{$post->title}}</a>
                    </h4>
                </li>
            @endforeach
        </ul>
        <div class="navi">
            <button class="up">
                <i class="fa fa-caret-left"></i>
            </button>
            <button class="down">
                <i class="fa fa-caret-right"></i>
            </button>
        </div>
    </div>
</div>

resources/views/partials/search-list.blade.php
@foreach($posts as $post)
    <div class="col-xs-12 col-sm-12 col-md-6 col-lg-4">
        <div class="container-half">
            <div class="entry-media">
                <div class="image" style="background-image: url({{thumbnail($post->image->path,'medium')}});">
                    <a href="{{$post->path}}" title="{{$post->title}}">
                        @if($post->format=='video')
                            <span class="play-icon"></span>
                        @elseif($post->format=="album")
                            <span class="play-icon album-icon"></span>
                        @endif
                    </a>
                </div>
            </div>
            <div class="content">
                <h4><a href="{{$post->path}}" title="{{$post->title}}">{{$post->title}}</a></h4>
            </div>
        </div>
    </div>
@endforeach

resources/views/partials/star-news.blade.php
<section class="module highlight" wp-site-content wp-body-class wp-site-name wp-title wp-site-desc wp-header-image>
    <div class="container">
        <div class="module-title">
            <h3 class="title"><span class="bg-13">نجوم الأخبار</span></h3>
        </div>
        <!--========== BEGIN .ROW ==========-->
        <div class="row no-gutter">
            @foreach($posts as $post)
                {!! $loop->index%2==0?'<div class="col-sm-6 col-md-6"> <div class="news star-news">':'' !!}
                <div class="item" itemscope itemtype="http://schema.org/Article">
                    <div class="item-image-1">
                        <a class="img-link" itemprop="url" content="{{$post->path}}" title="{{$post->title}}"
                           href="{{$post->path}}">
                            <img class="img-responsive img-full" src="{{thumbnail($post->image->path,'star-news')}}"
                                 title="{{$post->title}}" alt="{{$post->title}}">
                        </a>
                        <span><a class="label-1" style="background-color: {{$post->category->color}}"
                                 href="{{route('category.show',['slug'=>$post->category->slug])}}">{{$post->category->name}}</a></span>
                    </div>
                    <div class="item-content">
                        <div class="title-left title-style04 underline04">
                            <h3><a href="{{$post->path}}" title="{{$post->title}}"><strong
                                            itemprop="name">{{$post->title}}</strong></a>
                            </h3>
                        </div>
                        <p><a href="{{$post->path}}" class="external-link">{{$post->excerpt}}</a></p>

                        <div>
                            <a href="{{route('category.show',['slug'=>$post->category->slug])}}"><span
                                        class=" read-more"
                                        itemprop="articleSection">{{$post->category->name}}</span></a>
                        </div>
                    </div>
                </div>
                {!! $loop->index%2==1?'</div></div>':'' !!}
            @endforeach
        </div>
    </div>
</section>

resources/views/partials/survay.blade.php
@if($poll)
    <div class="survy-wapper" id="base-1">
        <div class="title-style02 survy-title">
            <h3><a href="javascript:void(0)">استطلاع الرأى</a></h3>
        </div>
        <div class="survy-question">
            <h3></h3>
        </div>
        <hr>
        <div class="row clearfix">
            <div class="answers"></div>
            <div class="results" style="display: none">
            </div>
        </div>
        <div class="btns">
            <button type="button" class="btn btn-lg btn-default vote" style="display: none">التصويت</button>
            <button type="button" class="btn btn-lg btn-default back" style="display: none">العودة</button>
            <button type="button" class="btn btn-lg btn-default show-result" style="display: none">النتائج</button>
        </div>

    </div>
@endif
@push('scripts')

    <script>
        $(function () {
            var model = {
                init() {
                    if (localStorage.getItem('vote_' + model.vote.id)) {
                        this.is_submit = true;
                    } else {
                        this.is_submit = false;
                    }
                },
                is_submit: false,
                vote: {!!  json_encode($poll) !!}
            }

            var presnter = {
                showResult: false,

                init() {
                    model.init();
                    view.init();
                },
                percentage(answers, total) {
                    return parseInt((answers / (total == 0 ? 1 : total)) * 100);
                },
                vote(vote_id) {
                    localStorage.setItem('vote_' + model.vote.id, vote_id);
                    model.vote.votes++;
                    model.vote.answers.find(function (e) {
                        return e.id == vote_id;
                    }).votes++;
                    model.is_submit = true;

                    $.ajaxSetup({headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')}});
                    $.ajax({
                        url: "{{route("poll.vote")}}",
                        type: 'POST',
                        data: {
                            'vote_id': vote_id
                        },
                        dataType: 'json',
                    })
                }

            }

            var view = {
                init() {
                    var $parent;
                    this.$parent = $parent = $('#base-1.survy-wapper');
                    this.$title = $parent.find('.survy-question h3');
                    this.$answers = $parent.find('.answers');
                    this.$results = $parent.find('.results');
                    this.$buttonResult = $parent.find('button.show-result');
                    this.$buttonVote = $parent.find('button.vote');
                    this.$buttonBack = $parent.find('button.back');

                    this.$title.html(model.vote.title);
                    this.$buttonResult.on('click', function (e) {
                        presnter.showResult = true;
                        view.render();
                    });

                    if (!model.is_submit) {
                        this.$buttonBack.on('click', function (e) {

                            presnter.showResult = false;
                            view.render();
                        });

                        this.$buttonVote.on('click', function (e) {
                            presnter.vote(view.$answers.find('input:checked').val());
                            view.renderResults();
                            view.render();
                        });

                        this.renderAnswers();
                    }
                    this.renderResults();
                    this.render()
                },


                render() {

                    this.$buttonResult.fadeOut();
                    this.$buttonVote.fadeOut();
                    this.$buttonBack.fadeOut();
                    if (presnter.showResult || model.is_submit) {
                        view.$buttonResult.fadeOut(300);
                        view.$buttonVote.fadeOut(300);
                        view.$answers.fadeOut(300, function () {
                            view.$results.fadeIn(300);
                            if (!model.is_submit) {
                                view.$buttonBack.fadeIn(300);

                            }
                        })
                    } else {
                        view.$buttonBack.fadeOut(300);
                        view.$results.fadeOut(300, function () {
                            view.$answers.fadeIn(300)
                            view.$buttonResult.fadeIn(300);
                            view.$buttonVote.fadeIn(300);
                        })
                    }
                },

                renderAnswers() {
                    var html = "";
                    for (var answer  of model.vote.answers) {
                        html += '  <label class="answer">' + answer.title +
                            '                <input type="radio" name="vote_' + model.vote.id + '" value="' + answer.id + '">' +
                            '                <span class="checkmark"></span>\n' +
                            '            </label><hr>';
                    }
                    $(html).hide().appendTo(this.$answers).fadeIn(600);
                },

                renderResults(show) {
                    var show = show || false;
                    var html = "";
                    for (var answer  of model.vote.answers) {
                        html += '<div class="answer">' +
                            '                <p>' + answer.title + '</p>' +
                            '                <div class="progress">' +
                            '                    <div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"\n' +
                            '                         style="min-width: 2em;width:' + presnter.percentage(answer.votes, model.vote.votes) + '%">' + presnter.percentage(answer.votes, model.vote.votes) + '%' +
                            '                    </div>' +
                            '                </div>' +
                            '            </div>' +
                            '            <hr>';
                    }
                    this.$results.html(html)
                }
            }

            presnter.init();

        })
    </script>

@endpush